export default [
    {
        id:'0',
        Category:'Alphabet',
        Image:require('../../Assets4/catg11.png')
    },
    {
        id:'1',
        Category:'Animal',
        Image:require('../../Assets4/catg2.png')
    },
    {
        id:'2',
        Category:'ArtMusic',
        Image:require('../../Assets4/catg51.png')
    },
    {
        id:'3',
        Category:'BodyParts',
        Image:require('../../Assets4/catg41.png')
    },
    {
        id:'4',
        Category:'Clothing',
        Image:require('../../Assets4/catg52.png')
    },
    {
        id:'5',
        Category:'Colors',
        Image:require('../../Assets4/catg22.png')
    },
    {
        id:'6',
        Category:'Food',
        Image:require('../../Assets4/catg1.png')
    },
    {
        id:'7',
        Category:'HomeItems',
        Image:require('../../Assets4/catg32.png')
    },
    {
        id:'8',
        Category:'Numbers',
        Image:require('../../Assets4/catg21.png')
    },
    {
        id:'9',
        Category:'OutdoorItems',
        Image:require('../../Assets4/catg42.png')
    },
    {
        id:'10',
        Category:'Shapes',
        Image:require('../../Assets4/catg31.png')
    },
    
    {
        id:'11',
        Category:'Transport',
        Image:require('../../Assets4/catg12.png')
    },
    {
        id:'12',
        Category:'More  ',
        Image:require('../../Assets4/catg61.png')
    },
    {
        id:'13',
        Category:'Review',
        Image:require('../../Assets4/catg62.png')
    },
]